#!/bin/python

import re
import urllib.request as urllibr

def download():
    return urllibr.urlopen("http://13wham.com/resources/ftptransfer/wham/closings/closings.html").read()

r = re.compile(b'<FONT CLASS="orgname">([a-zA-z0-9 ]+)</FONT>: <FONT CLASS="status">([a-zA-z0-9 ]+)</FONT>')
for t in r.findall(download()):
    print((t[0] + b': ' + t[1]).decode("utf-8"))
